[workspace]
resolver = "2"
members = ["src/config", "src/macros","src/courier", "src/logger", "src/server"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GNU GPLv3"
authors = ["Courier Team"]
description = "An extendable server software"
rust-version = "1.88"

[workspace.dependencies]
libc = "0.2.159"
