edition = "2024"

tab_spaces = 2
fn_params_layout = "Compressed"
hard_tabs = false
match_block_trailing_comma = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Max"

max_width = 2000