[package]
name = "courier"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
server = {path = "../server"}
utils = {path = "../utils"}
config = {path = "../config"}
macros ={ path = "../macros" }

libc.workspace = true

[build-dependencies]
git2 = "0.18"