[package]
name = "courier"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
build = "build.rs"

[dependencies]
server = { path = "../server"}
config = { path = "../config"}
macros = { path = "../macros" }
logger = { path = "../logger"}

libc.workspace = true
clap = {version =  "4.5.40", features = ["cargo", "derive"]}

[build-dependencies]
git2 = "0.20.2"