[package]
name = "utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
